import {
  AnimatedListDemo,
  AuroraDemo,
  BlurTextDemo,
  BorderGlowDemo,
  ClickSparkDemo,
  CountUpDemo,
  DockDemo,
  DotGridDemo,
  FadeContentDemo,
  FlowingMenuDemo,
  MagnetDemo,
  SplitTextDemo,
  SpotlightCardDemo,
  StepperDemo,
  ThreadsDemo
} from '../reactbits/adapters';
import { snippets } from './snippets';
import type { CategoryOption, EffectCatalogItem } from './types';

export const categories: CategoryOption[] = [
  { id: 'all', label: 'All' },
  { id: 'text', label: 'Text' },
  { id: 'interaction', label: 'Interaction' },
  { id: 'ui', label: 'UI' },
  { id: 'background', label: 'Background' }
];

export const effectCatalog: EffectCatalogItem[] = [
  {
    id: 'blur-text',
    name: 'BlurText',
    importName: 'BlurTextDemo',
    category: 'text',
    summary: 'Softly resolves blurred words into a crisp hero line.',
    bestFor: ['Hero headlines', 'Section intros', 'Launch messaging'],
    dependencies: ['React', 'motion'],
    component: BlurTextDemo,
    snippet: snippets.blurText,
    sourceUrl: 'https://reactbits.dev/text-animations/blur-text',
    motionIntensity: 'medium'
  },
  {
    id: 'split-text',
    name: 'SplitText',
    importName: 'SplitTextDemo',
    category: 'text',
    summary: 'Staggers words into place for a polished editorial reveal.',
    bestFor: ['Landing pages', 'Feature titles', 'Portfolio copy'],
    dependencies: ['React', 'gsap', '@gsap/react'],
    component: SplitTextDemo,
    snippet: snippets.splitText,
    sourceUrl: 'https://reactbits.dev/text-animations/split-text',
    motionIntensity: 'medium'
  },
  {
    id: 'count-up',
    name: 'CountUp',
    importName: 'CountUpDemo',
    category: 'text',
    summary: 'Animates numbers so metrics feel alive without extra decoration.',
    bestFor: ['Dashboards', 'KPIs', 'Impact stats'],
    dependencies: ['React', 'motion'],
    component: CountUpDemo,
    snippet: snippets.countUp,
    sourceUrl: 'https://reactbits.dev/text-animations/count-up',
    motionIntensity: 'low'
  },
  {
    id: 'fade-content',
    name: 'FadeContent',
    importName: 'FadeContentDemo',
    category: 'interaction',
    summary: 'Fades content into view with a clean upward motion.',
    bestFor: ['Progressive disclosure', 'Cards', 'Form sections'],
    dependencies: ['React'],
    component: FadeContentDemo,
    snippet: snippets.fadeContent,
    sourceUrl: 'https://reactbits.dev/animations/fade-content',
    motionIntensity: 'low'
  },
  {
    id: 'magnet',
    name: 'Magnet',
    importName: 'MagnetDemo',
    category: 'interaction',
    summary: 'Pulls a target subtly toward the pointer for tactile emphasis.',
    bestFor: ['Primary buttons', 'CTA links', 'Icon actions'],
    dependencies: ['React'],
    component: MagnetDemo,
    snippet: snippets.magnet,
    sourceUrl: 'https://reactbits.dev/animations/magnet',
    motionIntensity: 'medium'
  },
  {
    id: 'click-spark',
    name: 'ClickSpark',
    importName: 'ClickSparkDemo',
    category: 'interaction',
    summary: 'Adds a brief spark burst on click without changing layout.',
    bestFor: ['Buttons', 'Playable demos', 'Delight moments'],
    dependencies: ['React'],
    component: ClickSparkDemo,
    snippet: snippets.clickSpark,
    sourceUrl: 'https://reactbits.dev/animations/click-spark',
    motionIntensity: 'medium'
  },
  {
    id: 'spotlight-card',
    name: 'SpotlightCard',
    importName: 'SpotlightCardDemo',
    category: 'ui',
    summary: 'Adds pointer-aware lighting to a card surface.',
    bestFor: ['Feature cards', 'Pricing blocks', 'Portfolio tiles'],
    dependencies: ['React'],
    component: SpotlightCardDemo,
    snippet: snippets.spotlightCard,
    sourceUrl: 'https://reactbits.dev/components/spotlight-card',
    motionIntensity: 'medium'
  },
  {
    id: 'animated-list',
    name: 'AnimatedList',
    importName: 'AnimatedListDemo',
    category: 'ui',
    summary: 'Stages list items into view for activity and notification streams.',
    bestFor: ['Activity feeds', 'Notifications', 'Search results'],
    dependencies: ['React', 'motion'],
    component: AnimatedListDemo,
    snippet: snippets.animatedList,
    sourceUrl: 'https://reactbits.dev/components/animated-list',
    motionIntensity: 'low'
  },
  {
    id: 'dock',
    name: 'Dock',
    importName: 'DockDemo',
    category: 'ui',
    summary: 'Creates a compact icon dock with hover scale affordances.',
    bestFor: ['Toolbars', 'Creative apps', 'Navigation shortcuts'],
    dependencies: ['React', 'motion'],
    component: DockDemo,
    snippet: snippets.dock,
    sourceUrl: 'https://reactbits.dev/components/dock',
    motionIntensity: 'medium'
  },
  {
    id: 'border-glow',
    name: 'Border Glow',
    importName: 'BorderGlowDemo',
    category: 'ui',
    summary: 'Creates a cursor-directed mesh glow that intensifies near card edges.',
    bestFor: ['Featured panels', 'Upgrade prompts', 'Selected states'],
    dependencies: ['React'],
    component: BorderGlowDemo,
    snippet: snippets.borderGlow,
    sourceUrl: 'https://reactbits.dev/components/border-glow',
    motionIntensity: 'medium'
  },
  {
    id: 'stepper',
    name: 'Stepper',
    importName: 'StepperDemo',
    category: 'ui',
    summary: 'Shows a multi-step flow with animated progress feedback.',
    bestFor: ['Onboarding', 'Checkout', 'Setup flows'],
    dependencies: ['React', 'motion'],
    component: StepperDemo,
    snippet: snippets.stepper,
    sourceUrl: 'https://reactbits.dev/components/stepper',
    motionIntensity: 'low'
  },
  {
    id: 'flowing-menu',
    name: 'Flowing Menu',
    importName: 'FlowingMenuDemo',
    category: 'ui',
    summary: 'Turns menu choices into a fluid, highly visual navigation surface.',
    bestFor: ['Creative navigation', 'Category pickers', 'Showcase menus'],
    dependencies: ['React', 'gsap'],
    component: FlowingMenuDemo,
    snippet: snippets.flowingMenu,
    sourceUrl: 'https://reactbits.dev/components/flowing-menu',
    motionIntensity: 'high'
  },
  {
    id: 'aurora',
    name: 'Aurora',
    importName: 'AuroraDemo',
    category: 'background',
    summary: 'Layers soft moving color bands behind foreground content.',
    bestFor: ['Hero backgrounds', 'Event pages', 'Immersive sections'],
    dependencies: ['React', 'ogl'],
    component: AuroraDemo,
    snippet: snippets.aurora,
    sourceUrl: 'https://reactbits.dev/backgrounds/aurora',
    motionIntensity: 'high'
  },
  {
    id: 'dot-grid',
    name: 'DotGrid',
    importName: 'DotGridDemo',
    category: 'background',
    summary: 'Provides a crisp responsive dot matrix for technical layouts.',
    bestFor: ['Dashboards', 'Developer tools', 'Product backdrops'],
    dependencies: ['React', 'gsap'],
    component: DotGridDemo,
    snippet: snippets.dotGrid,
    sourceUrl: 'https://reactbits.dev/backgrounds/dot-grid',
    motionIntensity: 'low'
  },
  {
    id: 'threads',
    name: 'Threads',
    importName: 'ThreadsDemo',
    category: 'background',
    summary: 'Uses fine animated strands to create depth without heavy imagery.',
    bestFor: ['Ambient panels', 'AI products', 'Experimental pages'],
    dependencies: ['React', 'ogl'],
    component: ThreadsDemo,
    snippet: snippets.threads,
    sourceUrl: 'https://reactbits.dev/backgrounds/threads',
    motionIntensity: 'high'
  }
];
